

KEYS = {
    # 1. Bundesliga
    "VfL Wolfsburg",
    "VfB Stuttgart",
    "RB Leipzig",
    "FC Augsburg",
    "SC Freiburg",
    "FC St. Pauli",
    "FSV Mainz 05",
    "1. FC Heidenheim",
    "Bor. M'gladbach",
    "Union Berlin",
    "Bayern München",
    "Bayer leverkusen",
    "Holstein Kiel",
    "Eintracht Frankfurt",
    "TSG 1899 Hoffenheim",
    "Werder Bremen",
    "Borussia Dortmund",
    "VfL Bochum",
    # 2.Bundesliga
    "Preußen 06 Münster",
    "FC Schalke",
    "1. FC Köln",
    "Karlsruher SC",
    "Hannover 96",
    "1. FC Nürnberg",
    "Hertha BSC",
    "SV Elversberg",
    "SC Padernborn 07",
    "Jahn Regensburg",
    "SV Darmstadt 98",
    "SSV Ulm 1846",
    "1. FC Kaiserslautern",
    "1. FC Magdeburg",
    "Greuther Fürth",
    "Eintr. Braunschweig",
    "Fortuna Düsseldorf",
    "Hamburger SV",
    # 3. Bundesliga
    "SV Wehen Wies.",
    "VfL 1899 Osnabrück",
    "Hannover 96 II",
    "VfB Stuttgart II",
    "Borussia Dortmund II",
    "1860 München",
    "FC Viktoria Köln",
    "Erzgebirge Aue",
    "SV Waldhof M.",
    "RW Essen",
    "Energie Cottbus",
    "1. FC Saarbrücken",
    "FC Ingolstadt",
    "FC Hansa Rostock",
    "Dynamo Dresden",
    "Alemannia Aachen"
    "Arminia Bielefeld",
    "SC Verl",
    # Premier League
    "Brentford FC",
    "West Ham Utd",
    "Everton FC",
    "Crystal Palace",
    "FC Arsenal",
    "Leicester City",
    "FC Chelsea",
    "Brighton & Hove",
    "Nottingham Forest",
    "FC Fulham",
    "Wolverhampton",
    "FC Liverpool",
    "Ipswich Town",
    "Aston Villa",
    "Manchester United",
    "Tottenham Hotspur",
    "AFC Bournemouth",
    "Southampton FC",
    "Newcastle United",
    "Manchester City",
    # La Liga
    "Rayo Vallecano",
    "CD Leganes",
    "Real Sociedad",
    "CF Valencia",
    "CA Osasuna",
    "FC Barcelona",
    "RC Celta de Vigo",
    "Girona FC",
    "Athletic Bilbao",
    "FC Sevilla",
    "Real Betis",
    "Espanyol Barcelona",
    "Atletico Madrid",
    "Real Madrid",
    "Villarreal",
    "UD Las Palmas",
    "Alaves",
    "CF Getafe",
    "RCD Mallorca",
    "Real Valladolid",
    # Serie A
    "Udinese Calcio",
    "Inter Mailand",
    "Genua FC",
    "Juventus Turin",
    "Bologna FC",
    "Atalanta Bergamo",
    "FC Turin",
    "Lazio Rom",
    "AS Rom",
    "Venezia",
    "Como 1907",
    "Hellas Verona",
    "Empoli FC",
    "AC Florenz",
    "SSC Neapel",
    "AC Monza",
    "Parma Calcio",
    "Cagliari Calcio",
    "US Lecce",
    "AC Mailand",
    # Ligue 1
    "RC Lens",
    "OGC Nizza",
    "Le Havre AC",
    "OSC Lille",
    "AS Monaco",
    "Montpellier HSC",
    "FC Toulouse",
    "Olympique Lyon",
    "Angers SCO",
    "Stade de Reims",
    "FC Nantes",
    "AS Saint Etienne",
    "Racing Straßburg",
    "Olympique Marseille",
    "AJ Auxerre",
    "Paris SG",
    "Stade Brest 29",
    "Stade Rennes",

}